### ISSUE TITLE
no working in vscode

### ISSUE THREAD

**Issue by ZSkycat** [YuichiNukiyama/vscode-preview-server#24]
```
Visual Studio Code
Version 1.22.1
Commit 950b8b0d37a9b7061b6f0d291837ccc4015f5ecd
Date 2018-04-06T02:26:57.615Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

```
Preview on Web Server
1.0.1
```
![1](https://user-images.githubusercontent.com/20368649/38596305-5a0fad34-3d83-11e8-8cdd-946308d36086.gif)

**Comment by YuichiNukiyama** [comment]
It runs in my environment.
Please tell me reporuduce step. Or see Help > toggle developer tool, and send message of console to me.

**Comment by ZSkycat** [comment]
![image](https://user-images.githubusercontent.com/20368649/38618434-38d58938-3dcc-11e8-8da3-19b8457981b8.png)

```
workbench.main.js:sourcemap:2867 激活扩展“yuichinukiyama.vscode-preview-server”失败: Invalid or unexpected token。
w._logMessageInConsole @ workbench.main.js:sourcemap:2867
w._logOrShowMessage @ workbench.main.js:sourcemap:2867
e.$localShowMessage @ workbench.main.js:sourcemap:2869
e._doInvokeHandler @ workbench.main.js:sourcemap:2848
e._invokeHandler @ workbench.main.js:sourcemap:2848
e._receiveRequest @ workbench.main.js:sourcemap:2847
e._receiveOneMessage @ workbench.main.js:sourcemap:2847
(anonymous) @ workbench.main.js:sourcemap:2846
(anonymous) @ workbench.main.js:sourcemap:2849
e.fire @ workbench.main.js:sourcemap:166
(anonymous) @ workbench.main.js:sourcemap:291
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
```

```
激活扩展“yuichinukiyama.vscode-preview-server”失败: Invalid or unexpected token。
w._logMessageInConsole @ workbench.main.js:sourcemap:2867
w._logOrShowMessage @ workbench.main.js:sourcemap:2867
e.$localShowMessage @ workbench.main.js:sourcemap:2869
e._doInvokeHandler @ workbench.main.js:sourcemap:2848
e._invokeHandler @ workbench.main.js:sourcemap:2848
e._receiveRequest @ workbench.main.js:sourcemap:2847
e._receiveOneMessage @ workbench.main.js:sourcemap:2847
(anonymous) @ workbench.main.js:sourcemap:2846
(anonymous) @ workbench.main.js:sourcemap:2849
e.fire @ workbench.main.js:sourcemap:166
(anonymous) @ workbench.main.js:sourcemap:291
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
workbench.main.js:sourcemap:2217 command 'extension.launch' not found
e.onDidNotificationChange @ workbench.main.js:sourcemap:2217
(anonymous) @ workbench.main.js:sourcemap:2217
e.fire @ workbench.main.js:sourcemap:166
e.notify @ workbench.main.js:sourcemap:2210
e.error @ workbench.main.js:sourcemap:3037
t.onError @ workbench.main.js:sourcemap:3810
(anonymous) @ workbench.main.js:sourcemap:3810
done @ workbench.main.js:sourcemap:152
v @ workbench.main.js:sourcemap:147
enter @ workbench.main.js:sourcemap:150
_run @ workbench.main.js:sourcemap:151
_chainedError @ workbench.main.js:sourcemap:151
n @ workbench.main.js:sourcemap:148
then @ workbench.main.js:sourcemap:152
enter @ workbench.main.js:sourcemap:149
_run @ workbench.main.js:sourcemap:151
_setCompleteValue @ workbench.main.js:sourcemap:151
g @ workbench.main.js:sourcemap:146
enter @ workbench.main.js:sourcemap:149
_run @ workbench.main.js:sourcemap:151
_completed @ workbench.main.js:sourcemap:151
l @ workbench.main.js:sourcemap:154
n.Class.derive.join.o.forEach.j.then.r.(anonymous function) @ workbench.main.js:sourcemap:154
g @ workbench.main.js:sourcemap:146
enter @ workbench.main.js:sourcemap:149
_run @ workbench.main.js:sourcemap:151
_completed @ workbench.main.js:sourcemap:151
g @ workbench.main.js:sourcemap:146
enter @ workbench.main.js:sourcemap:149
_run @ workbench.main.js:sourcemap:151
_completed @ workbench.main.js:sourcemap:151
e.resolveOk @ workbench.main.js:sourcemap:2793
e._receiveReply @ workbench.main.js:sourcemap:2847
e._receiveOneMessage @ workbench.main.js:sourcemap:2847
(anonymous) @ workbench.main.js:sourcemap:2846
(anonymous) @ workbench.main.js:sourcemap:2849
e.fire @ workbench.main.js:sourcemap:166
(anonymous) @ workbench.main.js:sourcemap:291
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
```

```
command 'extension.launch' not found
e.onDidNotificationChange @ workbench.main.js:sourcemap:2217
(anonymous) @ workbench.main.js:sourcemap:2217
e.fire @ workbench.main.js:sourcemap:166
e.notify @ workbench.main.js:sourcemap:2210
e.error @ workbench.main.js:sourcemap:3037
t.onError @ workbench.main.js:sourcemap:3810
(anonymous) @ workbench.main.js:sourcemap:3810
done @ workbench.main.js:sourcemap:152
v @ workbench.main.js:sourcemap:147
enter @ workbench.main.js:sourcemap:150
_run @ workbench.main.js:sourcemap:151
_chainedError @ workbench.main.js:sourcemap:151
n @ workbench.main.js:sourcemap:148
then @ workbench.main.js:sourcemap:152
enter @ workbench.main.js:sourcemap:149
_run @ workbench.main.js:sourcemap:151
_setCompleteValue @ workbench.main.js:sourcemap:151
g @ workbench.main.js:sourcemap:146
enter @ workbench.main.js:sourcemap:149
_run @ workbench.main.js:sourcemap:151
_completed @ workbench.main.js:sourcemap:151
l @ workbench.main.js:sourcemap:154
n.Class.derive.join.o.forEach.j.then.r.(anonymous function) @ workbench.main.js:sourcemap:154
g @ workbench.main.js:sourcemap:146
enter @ workbench.main.js:sourcemap:149
_run @ workbench.main.js:sourcemap:151
_completed @ workbench.main.js:sourcemap:151
g @ workbench.main.js:sourcemap:146
enter @ workbench.main.js:sourcemap:149
_run @ workbench.main.js:sourcemap:151
_completed @ workbench.main.js:sourcemap:151
e.resolveOk @ workbench.main.js:sourcemap:2793
e._receiveReply @ workbench.main.js:sourcemap:2847
e._receiveOneMessage @ workbench.main.js:sourcemap:2847
(anonymous) @ workbench.main.js:sourcemap:2846
(anonymous) @ workbench.main.js:sourcemap:2849
e.fire @ workbench.main.js:sourcemap:166
(anonymous) @ workbench.main.js:sourcemap:291
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
workbench.main.js:sourcemap:260 [Extension Host] Activating extension `yuichinukiyama.vscode-preview-server` failed:  Invalid or unexpected token
t.log @ workbench.main.js:sourcemap:260
t._logExtensionHostMessage @ workbench.main.js:sourcemap:2779
(anonymous) @ workbench.main.js:sourcemap:2775
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
```

```
[Extension Host] Here is the error stack:  C:\Users\Cat\.vscode\extensions\yuichinukiyama.vscode-preview-server-1.0.1\node_modules\lodash\index.js:2333
        return �0�a:3=���`7��\��y��Ӱ
               ^
SyntaxError: Invalid or unexpected token
	at createScript (vm.js:53:10)
	at Object.runInThisContext (vm.js:95:10)
	at Module._compile (module.js:543:28)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:653:398)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\Cat\.vscode\extensions\yuichinukiyama.vscode-preview-server-1.0.1\node_modules\easy-extender\index.js:1:164)
	at Object.<anonymous> (C:\Users\Cat\.vscode\extensions\yuichinukiyama.vscode-preview-server-1.0.1\node_modules\easy-extender\index.js:208:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:653:398)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\Cat\.vscode\extensions\yuichinukiyama.vscode-preview-server-1.0.1\node_modules\browser-sync\dist\utils.js:288:31)
	at Object.<anonymous> (C:\Users\Cat\.vscode\extensions\yuichinukiyama.vscode-preview-server-1.0.1\node_modules\browser-sync\dist\utils.js:290:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:653:398)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\Cat\.vscode\extensions\yuichinukiyama.vscode-preview-server-1.0.1\node_modules\browser-sync\dist\snippet.js:7:13)
	at Object.<anonymous> (C:\Users\Cat\.vscode\extensions\yuichinukiyama.vscode-preview-server-1.0.1\node_modules\browser-sync\dist\snippet.js:92:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:653:398)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\Cat\.vscode\extensions\yuichinukiyama.vscode-preview-server-1.0.1\node_modules\browser-sync\dist\hooks.js:4:20)
	at Object.<anonymous> (C:\Users\Cat\.vscode\extensions\yuichinukiyama.vscode-preview-server-1.0.1\node_modules\browser-sync\dist\hooks.js:82:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:653:398)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\Cat\.vscode\extensions\yuichinukiyama.vscode-preview-server-1.0.1\node_modules\browser-sync\dist\browser-sync.js:2:13)
	at Object.<anonymous> (C:\Users\Cat\.vscode\extensions\yuichinukiyama.vscode-preview-server-1.0.1\node_modules\browser-sync\dist\browser-sync.js:566:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:653:398)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\Cat\.vscode\extensions\yuichinukiyama.vscode-preview-server-1.0.1\node_modules\browser-sync\dist\index.js:7:19)
	at Object.<anonymous> (C:\Users\Cat\.vscode\extensions\yuichinukiyama.vscode-preview-server-1.0.1\node_modules\browser-sync\dist\index.js:349:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:653:398)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\Cat\.vscode\extensions\yuichinukiyama.vscode-preview-server-1.0.1\out\src\server.js:3:21)
	at Object.<anonymous> (C:\Users\Cat\.vscode\extensions\yuichinukiyama.vscode-preview-server-1.0.1\out\src\server.js:60:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:653:398)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\Cat\.vscode\extensions\yuichinukiyama.vscode-preview-server-1.0.1\out\src\extension.js:5:18)
	at Object.<anonymous> (C:\Users\Cat\.vscode\extensions\yuichinukiyama.vscode-preview-server-1.0.1\out\src\extension.js:129:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:653:398)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Function.i [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:30:770)
```

**Comment by ZSkycat** [comment]
@YuichiNukiyama 
This should be related to my computer.
After I changed a computer, it can worked.

**Comment by ZSkycat** [comment]
delete `%USERPROFILE%\.vscode\extensions\yuichinukiyama.vscode-preview-server-1.0.1`
then reinstall
it can working
I think the file is damaged
